# eXBuilder6 API 설정 파일
# 버전별 API 정보를 관리하는 설정 파일

versions:
  "6.0":
    grd:
      methods:
        - addRow
        - deleteRow
        - updateRow
        - getRow
        - getData
        - setData
        - clear
        - refresh
        - getSelected
        - setSelected
        - getChecked
        - setChecked
        - getExpanded
        - setExpanded
        - scrollTo
        - scrollIntoView
        - enable
        - disable
        - show
        - hide
        - focus
        - blur
        - getCellInfo
        - setCellInfo
        - getRowData
        - setRowData
        - getColumnData
        - setColumnData
        - getHeaderData
        - setHeaderData
        - getFooterData
        - setFooterData
        - getSummaryData
        - setSummaryData
        - insertRowData
        - removeRowData
        - getRowCount
        - getColumnCount
        - getSelectedRows
        - setSelectedRows
        - getSelectedRow
        - getSelectedRowIndex
        - setSelectedRowIndex
        - getCellValue
        - setCellValue
        - getCellText
        - setCellText
        - getCellStyle
        - setCellStyle
        - getColumnWidth
        - setColumnWidth
        - getRowHeight
        - setRowHeight
        - getVisibleRows
        - setVisibleRows
        - getVisibleColumns
        - setVisibleColumns
        - getSortColumn
        - setSortColumn
        - getSortOrder
        - setSortOrder
        - getFilterData
        - setFilterData
        - getGroupData
        - setGroupData
        - getPagingData
        - setPagingData
        - getPageSize
        - setPageSize
        - getCurrentPage
        - setCurrentPage
        - getTotalCount
        - setTotalCount
        - getPageCount
        - setPageCount
        - getPageInfo
        - setPageInfo
        - getCurrentRow
        - setCurrentRow
        - getCurrentRowIndex
        - setCurrentRowIndex
        - getRowByIndex
        - getRowByData
        - findRow
        - findRows
        - selectRow
        - selectRows
        - deselectRow
        - deselectRows
        - selectAll
        - deselectAll
        - isRowSelected
        - isRowChecked
        - isRowExpanded
        - expandRow
        - collapseRow
        - expandAll
        - collapseAll
      properties:
        - text
        - value
        - visible
        - enabled
        - readOnly
        - width
        - height
        - style
        - data
        - columns
        - rows
        - selectedIndex
        - selectedIndices
        - selectedRow
        - selectedRows
        - currentRow
        - currentColumn
        - rowCount
        - columnCount
        - pageSize
        - currentPage
        - totalCount
        - pageCount
        - sortColumn
        - sortOrder
        - filterData
        - groupData
        - summaryData
        - pagingData
        - editable
        - selectable
        - multiSelect
        - checkable
        - expandable
        - resizable
        - draggable
        - droppable
        - scrollable
        - paging
        - sorting
        - filtering
        - grouping
        - summarizing
        - exporting
        - importing
        - printing
      events:
        - onCellClick
        - onCellDoubleClick
        - onCellRightClick
        - onHeaderClick
        - onRowClick
        - onRowDoubleClick
        - onRowRightClick
        - onSelectionChanged
        - onDataChanged
        - onCellEdit
        - onCellEditEnd
        - onCellEditCancel
        - onRowAdded
        - onRowDeleted
        - onRowUpdated
        - onColumnResized
        - onColumnMoved
        - onColumnSorted
        - onColumnFiltered
        - onColumnGrouped
        - onPageChanged
        - onPageSizeChanged
        - onScroll
        - onFocus
        - onBlur
        - onKeyDown
        - onKeyUp

    button:
      methods:
        - setText
        - getText
        - enable
        - disable
        - show
        - hide
        - focus
        - blur
        - click
        - setIcon
        - getIcon
        - setIconAlign
        - getIconAlign
        - setButtonType
        - getButtonType
        - setImage
        - getImage
        - setImageAlign
        - getImageAlign
        - setTooltip
        - getTooltip
      properties:
        - text
        - value
        - visible
        - enabled
        - readOnly
        - width
        - height
        - style
        - icon
        - iconAlign
        - buttonType
        - image
        - imageAlign
        - tooltip
        - defaultButton
        - cancelButton
        - flat
        - raised
        - outlined
        - textOnly
        - iconOnly
        - textAndIcon
      events:
        - onClick
        - onDoubleClick
        - onRightClick
        - onMouseDown
        - onMouseUp
        - onMouseOver
        - onMouseOut
        - onFocus
        - onBlur
        - onKeyDown
        - onKeyUp

    btn:
      methods:
        - setText
        - getText
        - enable
        - disable
        - show
        - hide
        - focus
        - blur
        - click
        - setIcon
        - getIcon
        - setIconAlign
        - getIconAlign
        - setButtonType
        - getButtonType
        - setImage
        - getImage
        - setImageAlign
        - getImageAlign
        - setTooltip
        - getTooltip
      properties:
        - text
        - value
        - visible
        - enabled
        - readOnly
        - width
        - height
        - style
        - icon
        - iconAlign
        - buttonType
        - image
        - imageAlign
        - tooltip
        - defaultButton
        - cancelButton
        - flat
        - raised
        - outlined
        - textOnly
        - iconOnly
        - textAndIcon
      events:
        - onClick
        - onDoubleClick
        - onRightClick
        - onMouseDown
        - onMouseUp
        - onMouseOver
        - onMouseOut
        - onFocus
        - onBlur
        - onKeyDown
        - onKeyUp

    cmb:
      methods:
        - addItem
        - deleteItem
        - updateItem
        - getItem
        - getData
        - setData
        - clear
        - refresh
        - getSelected
        - setSelected
        - getChecked
        - setChecked
        - enable
        - disable
        - show
        - hide
        - focus
        - blur
        - openDropdown
        - closeDropdown
        - getSelectedIndex
        - setSelectedIndex
        - getSelectedValue
        - setSelectedValue
        - getSelectedText
        - setSelectedText
        - getItemCount
        - getItemText
        - setItemText
        - getItemValue
        - setItemValue
        - getItemData
        - setItemData
        - getItemIndex
        - setItemIndex
        - getItemByValue
        - getItemByText
        - getItemByIndex
      properties:
        - text
        - value
        - visible
        - enabled
        - readOnly
        - width
        - height
        - style
        - items
        - selectedIndex
        - selectedValue
        - selectedText
        - dropdownVisible
        - itemCount
        - maxDropDownItems
        - dropDownWidth
        - dropDownHeight
        - autoComplete
        - caseSensitive
        - filterMode
        - sortMode
        - editable
        - allowCustom
        - allowNull
        - placeholder
      events:
        - onClick
        - onDoubleClick
        - onRightClick
        - onSelectionChanged
        - onDropdownOpened
        - onDropdownClosed
        - onItemSelected
        - onItemDeselected
        - onTextChanged
        - onFocus
        - onBlur

    cbx:
      methods:
        - setChecked
        - getChecked
        - setText
        - getText
        - enable
        - disable
        - show
        - hide
        - focus
        - blur
        - setCheckType
        - getCheckType
        - setTextAlign
        - getTextAlign
        - setGroupName
        - getGroupName
      properties:
        - text
        - value
        - visible
        - enabled
        - readOnly
        - width
        - height
        - style
        - checked
        - checkType
        - textAlign
        - groupName
        - threeState
        - indeterminate
        - autoCheck
        - allowGrayed
        - flat
        - raised
        - outlined
      events:
        - onClick
        - onDoubleClick
        - onRightClick
        - onCheckedChanged
        - onIndeterminateChanged
        - onFocus
        - onBlur
        - onKeyDown
        - onKeyUp

    ipb:
      methods:
        - setValue
        - getValue
        - setText
        - getText
        - enable
        - disable
        - show
        - hide
        - focus
        - blur
        - setMaxLength
        - getMaxLength
        - setPlaceholder
        - getPlaceholder
        - setInputType
        - getInputType
        - setPattern
        - getPattern
        - setRequired
        - getRequired
        - setReadOnly
        - getReadOnly
        - setAutoComplete
        - getAutoComplete
        - setAutoFocus
        - getAutoFocus
        - setSpellCheck
        - getSpellCheck
      properties:
        - text
        - value
        - visible
        - enabled
        - readOnly
        - width
        - height
        - style
        - maxLength
        - placeholder
        - inputType
        - pattern
        - required
        - autoComplete
        - autoFocus
        - spellCheck
        - min
        - max
        - step
        - size
        - multiple
        - accept
      events:
        - onValueChanged
        - onTextChanged
        - onKeyDown
        - onKeyUp
        - onKeyPress
        - onInput
        - onChange
        - onFocus
        - onBlur
        - onSelect
        - onInvalid
        - onReset
        - onSubmit

# 공통 API (모든 컨트롤에서 사용 가능)
common_apis:
  methods:
    - setValue
    - getValue
    - setText
    - getText
    - enable
    - disable
    - show
    - hide
    - focus
    - blur
    - setVisible
    - getVisible
    - setEnabled
    - getEnabled
    - setReadOnly
    - getReadOnly
    - setWidth
    - getWidth
    - setHeight
    - getHeight
    - setStyle
    - getStyle
    - setData
    - getData
    - refresh
    - clear
    - reset
    - validate
    - isValid
    - getParent
    - getChild
    - getChildren
    - getSibling
    - getSiblings
    - getRoot
    - getAncestor
    - getDescendant
    - getFirstChild
    - getLastChild
    - getNextSibling
    - getPreviousSibling
    - addChild
    - removeChild
    - insertChild
  properties:
    - text
    - value
    - visible
    - enabled
    - readOnly
    - width
    - height
    - style
    - data
    - name
    - id
    - className
    - tagName
    - parentNode
    - childNodes
    - firstChild
    - lastChild
    - nextSibling
    - previousSibling
    - nodeType
    - nodeValue
    - nodeName
    - attributes
  events:
    - onLoad
    - onUnload
    - onClick
    - onDoubleClick
    - onRightClick
    - onMouseDown
    - onMouseUp
    - onMouseOver
    - onMouseOut
    - onMouseMove
    - onMouseEnter
    - onMouseLeave
    - onFocus
    - onBlur
    - onKeyDown
    - onKeyUp
    - onKeyPress
    - onChange
    - onSelect
    - onInput
    - onInvalid
    - onReset
    - onSubmit
    - onError
    - onAbort
    - onResize
    - onScroll
    - onContextMenu

# 메시지 API
message_apis:
  methods:
    - showMessage
    - showConfirm
    - showAlert
    - showError
    - showWarning
    - showInfo
    - showSuccess
    - showQuestion
    - showInput
    - showSelect
    - showFileDialog
    - showColorDialog
    - showFontDialog
    - openPopup
    - closePopup
    - showPopup
    - hidePopup
    - setPopupPosition
    - getPopupPosition
    - setPopupSize
    - getPopupSize
    - setPopupTitle
    - getPopupTitle
    - setPopupContent
    - getPopupContent

# 데이터 API
data_apis:
  methods:
    - getData
    - setData
    - getJsonData
    - setJsonData
    - getXmlData
    - setXmlData
    - getCsvData
    - setCsvData
    - loadData
    - saveData
    - exportData
    - importData
    - validateData
    - transformData
    - filterData
    - sortData
    - groupData
    - aggregateData
    - calculateData
    - mergeData
    - splitData
    - cloneData
